from __future__ import annotations

import re
from typing import Any, Literal, TypedDict


class AgentState(TypedDict, total=False):
    action: Literal["analyse", "migrate", "patterns"]
    snippet_id: str
    code: str
    query: str | None
    analysis: str
    migration: dict[str, Any]
    patterns: dict[str, Any]


def _detect_language(code: str) -> str:
    lowered = code.lower()
    if "public static void main" in lowered or "system.out.println" in lowered:
        return "java"
    if "def " in lowered or "print(" in lowered:
        return "python"
    if "function " in lowered or "console.log" in lowered:
        return "javascript"
    if "#include" in lowered:
        return "c/c++"
    return "unknown"


def _detect_antipatterns(code: str) -> list[str]:
    checks = [
        (r"\beval\s*\(", "Dynamic evaluation can execute unsafe input."),
        (r"printStackTrace\s*\(", "Raw stack traces leak implementation details."),
        (r"SELECT\s+.*\+.*FROM|FROM\s+.*\+", "String-built SQL can cause injection risks."),
        (r"\bcatch\s*\([^)]*\)\s*\{\s*\}", "Empty catch blocks hide failures."),
        (r"\bvar\s+", "Broad variable declarations can reduce type clarity in legacy JavaScript."),
        (r"new\s+Thread\s*\(", "Manual thread creation can make concurrency hard to govern."),
    ]
    found = [message for pattern, message in checks if re.search(pattern, code, re.IGNORECASE | re.DOTALL)]
    return found or ["No high-confidence anti-patterns detected by the placeholder rules."]


def _analyse_node(state: AgentState) -> AgentState:
    code = state["code"]
    query = state.get("query")
    language = _detect_language(code)
    antipatterns = _detect_antipatterns(code)
    lines = len(code.splitlines())

    focus = f"\n\n## User Focus\n{query.strip()}" if query else ""
    bullets = "\n".join(f"- {item}" for item in antipatterns)
    state["analysis"] = (
        f"## Legacy Code Analysis\n\n"
        f"- **Detected language:** {language}\n"
        f"- **Approximate size:** {lines} line(s)\n"
        f"- **Purpose:** The snippet appears to contain executable logic that should be reviewed for "
        f"modern language features, clearer error handling, and safer dependency boundaries."
        f"{focus}\n\n"
        f"## Anti-Patterns And Risks\n{bullets}\n\n"
        f"## Modernisation Direction\n"
        f"- Preserve externally visible behaviour before refactoring.\n"
        f"- Add tests around current behaviour before changing implementation details.\n"
        f"- Replace unsafe or legacy constructs with typed, validated, maintainable alternatives."
    )
    return state


def _migrate_node(state: AgentState) -> AgentState:
    code = state["code"]
    language = _detect_language(code)
    modernized_code = (
        "# Modernised version generated by the integration placeholder.\n"
        "# Replace this deterministic output with an LLM-backed LangGraph node.\n\n"
        f"{code.strip()}\n"
    )
    state["migration"] = {
        "snippet_id": state["snippet_id"],
        "modernized_code": modernized_code,
        "language": language,
        "summary": "Generated a behaviour-preserving modernisation draft using the integration workflow.",
        "checklist": [
            {
                "item": "Preserve existing behaviour",
                "status": "review_required",
                "notes": "Add or run regression tests before accepting the migrated code.",
            },
            {
                "item": "Improve readability and maintainability",
                "status": "changed",
                "notes": "Placeholder output marks where LLM-backed transformations will be applied.",
            },
            {
                "item": "Validate runtime compatibility",
                "status": "review_required",
                "notes": "Review framework, dependency, and deployment differences manually.",
            },
        ],
        "risks": [
            {
                "risk": "Generated code has not been compiled or executed.",
                "severity": "medium",
                "mitigation": "Run language-specific unit, integration, and smoke tests.",
            }
        ],
    }
    return state


def _patterns_node(state: AgentState) -> AgentState:
    state["patterns"] = {
        "patterns": [
            {
                "name": "String-built SQL",
                "description": "Queries assembled with string concatenation are difficult to validate and may allow injection.",
                "example": "SELECT * FROM users WHERE id = ' + userInput",
                "modern_alternative": "Use parameterized queries or an ORM query builder.",
            },
            {
                "name": "Swallowed exceptions",
                "description": "Empty catch blocks hide failures and make migrations risky.",
                "example": "catch (Exception e) {}",
                "modern_alternative": "Handle expected errors explicitly and log unexpected failures.",
            },
            {
                "name": "Unsafe dynamic execution",
                "description": "Dynamic evaluation executes code paths that are hard to inspect or secure.",
                "example": "eval(userInput)",
                "modern_alternative": "Use typed command maps, parsers, or validated configuration.",
            },
        ]
    }
    return state


def _fallback_invoke(state: AgentState) -> AgentState:
    action = state["action"]
    if action == "analyse":
        return _analyse_node(state)
    if action == "migrate":
        return _migrate_node(state)
    if action == "patterns":
        return _patterns_node(state)
    raise ValueError(f"Unsupported graph action: {action}")


def _build_graph():
    try:
        from langgraph.graph import END, StateGraph
    except ImportError:
        return None

    graph = StateGraph(AgentState)
    graph.add_node("analyse", _analyse_node)
    graph.add_node("migrate", _migrate_node)
    graph.add_node("patterns", _patterns_node)

    graph.set_conditional_entry_point(
        lambda state: state["action"],
        {
            "analyse": "analyse",
            "migrate": "migrate",
            "patterns": "patterns",
        },
    )
    graph.add_edge("analyse", END)
    graph.add_edge("migrate", END)
    graph.add_edge("patterns", END)
    return graph.compile()


_GRAPH = _build_graph()


def invoke_graph(state: AgentState) -> AgentState:
    if _GRAPH is None:
        return _fallback_invoke(state)
    return _GRAPH.invoke(state)
