import os

from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from langgraph.types import interrupt

from prompts.generator_prompt import GENERATOR_PROMPT
from schemas.output_schemas import ModernCodeOutput
from state import AgentState


load_dotenv("backend/.env")


def _fallback_code(state: AgentState) -> dict:
    raw_code = state.get("raw_code", "").strip()
    modern_code = (
        '"""Modernisation draft generated by deterministic fallback rules."""\n\n'
        "from fastapi import FastAPI\n\n"
        "app = FastAPI()\n\n\n"
        "@app.get('/legacy-behaviour')\n"
        "def legacy_behaviour() -> dict:\n"
        "    # Preserves the reviewed legacy snippet as reference while replacing direct response writes with a typed API response.\n"
        f"    legacy_reference = {raw_code!r}\n"
        "    # Returns structured JSON so callers receive a modern, testable contract.\n"
        "    return {'status': 'modernised', 'legacy_reference': legacy_reference}\n"
    )
    return {
        "modern_code": modern_code,
        "changes_made": [
            "Wrapped legacy behaviour in a FastAPI endpoint.",
            "Returned structured JSON instead of direct response output.",
            "Kept the original snippet as a reference for reviewer validation.",
        ],
    }


async def generate_modern_code(state: AgentState) -> dict:
    """Generate modern code after approved analysis and pause for code review."""
    if not state.get("human_approved_analysis"):
        return {"error": "Analysis not approved"}

    if not os.getenv("OPENAI_API_KEY"):
        generated = _fallback_code(state)
        interrupt(
            {
                "message": "Review generated code. Set human_approved_code=True to continue.",
                "generated_code": generated,
            }
        )
        return generated

    llm = ChatOpenAI(model="gpt-4o", temperature=0.2)
    structured_llm = llm.with_structured_output(ModernCodeOutput)
    chain = GENERATOR_PROMPT | structured_llm
    target_framework = state.get("target_framework", "Python/FastAPI")
    result = await chain.ainvoke(
        {
            "raw_code": state["raw_code"],
            "language": state.get("language", "unknown"),
            "target_framework": target_framework,
            "identified_patterns": state.get("identified_patterns", []),
            "risk_report": state.get("risk_report", {}),
        }
    )
    modern_code = result.modern_code
    generated = {
        "modern_code": modern_code,
        "changes_made": result.changes_made,
    }
    interrupt(
        {
            "message": "Review generated code. Set human_approved_code=True to continue.",
            "generated_code": generated,
        }
    )
    return generated
